services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.production

  web:
    build: ./thesis
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    expose:
      - 8000
    environment:
      - ENVIRONMENT=production
    env_file:
      - ./.env.production

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
