services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - path: ./.env.production
        required: true

  web:
    build: ./thesis
    volumes:
      - ${STATICFILES_PATH}:/app/staticfiles
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=production
    env_file:
      - path: ./.env.production
        required: true

volumes:
  postgres_data:
