name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install compose
      run: |
        sudo curl -L \
          "https://github.com/docker/compose/releases/download/2.23.3/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Setup environment
      run: cp .env.example .env.production

    - name: Build and run containers
      run: |
        docker compose up -d --build
        docker compose exec web python manage.py migrate --noinput
        docker compose exec web python manage.py collectstatic --noinput

    - name: Run tests
      run: docker compose exec web python manage.py test

    - name: Stop and remove containers
      run: docker compose down -v
