name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and run containers
      run: |
        cp .env.example .env
        docker-compose up -d --build
        docker-compose exec web python manage.py migrate --noinput
        docker-compose exec web python manage.py collectstatic --noinput
        docker-compose exec web python manage.py test

    - name: Stop and remove containers
      run: docker-compose down -v
